// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAC-dbqNwYf3d4qmXrOpN4rHChjSYqWBs',
    appId: '1:297866685320:web:6e2a4b25628d2fe095e83d',
    messagingSenderId: '297866685320',
    projectId: 'push-app-flutter-fe20e',
    authDomain: 'push-app-flutter-fe20e.firebaseapp.com',
    storageBucket: 'push-app-flutter-fe20e.appspot.com',
    measurementId: 'G-CC66H3BES5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDifoucLutswHEJ8sKClBoKeFyGydmmgQ',
    appId: '1:297866685320:android:d3d82ea0de3b9f7795e83d',
    messagingSenderId: '297866685320',
    projectId: 'push-app-flutter-fe20e',
    storageBucket: 'push-app-flutter-fe20e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLGHU0BOufIGgKzdA2BEgHVqReTD0HOdU',
    appId: '1:297866685320:ios:5f99910ac3d9b40a95e83d',
    messagingSenderId: '297866685320',
    projectId: 'push-app-flutter-fe20e',
    storageBucket: 'push-app-flutter-fe20e.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLGHU0BOufIGgKzdA2BEgHVqReTD0HOdU',
    appId: '1:297866685320:ios:f2dffaa78f78404695e83d',
    messagingSenderId: '297866685320',
    projectId: 'push-app-flutter-fe20e',
    storageBucket: 'push-app-flutter-fe20e.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
